[build]
  publish = "live_build"
  command = ""

[[redirects]]
  from = "/chatbot"
  to = "https://poet-dzal.onrender.com/chatbot"
  status = 200
  force = true

[[redirects]]
  from = "/chatbot_reset"
  to = "https://poet-dzal.onrender.com/chatbot_reset"
  status = 200
  force = true
